name: kachaka_api
description: kachaka-api
homepage: https://github.com/pf-robotics/kachaka-api
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
